First setup with bootify
SpringBooty/SpringBooty pull request #8
Opened 2023-12-30 20:48 UTC by TheHassanAli2

Created base schema, need to figure out if we can change the invitee to event relation to combined primary key table instead of its own key (still works, design is bad though).

2024-01-04 20:05 UTC, Iman1121 approved these changes

2024-01-04 20:05 UTC, Iman1121 approved these changes

2024-01-05 21:57 UTC, Iman1121 approved these changes

2024-01-05 21:59 UTC, kunwar45 approved these changes

2024-01-05 22:01 UTC, kunwar45 requested changes

2024-01-05 22:01 UTC, kunwar45 commented on .gitignore
> +.idea/
the .idea file is included

2024-01-05 22:01 UTC, kunwar45 commented on event-planner/.gitignore
> +HELP.md
no two gitignore

2024-01-05 22:01 UTC, kunwar45 approved these changes

2024-01-05 22:07 UTC, merged